# Generated by Django 2.1.1 on 2019-06-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=30, verbose_name='地址')),
                ('name', models.CharField(max_length=10, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '用户地址管理',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[('男', 1), ('女', 0)], verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('life', models.CharField(max_length=30, verbose_name='现居地')),
                ('addrs', models.ManyToManyField(to='users.Address', verbose_name='地址管理')),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息管理',
            },
        ),
    ]
