# Generated by Django 2.1.1 on 2019-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='c_datatime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='u_datatime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
