# Generated by Django 2.2.1 on 2019-06-25 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='描述')),
                ('color', models.CharField(max_length=20, unique=True, verbose_name='色值')),
            ],
        ),
        migrations.CreateModel(
            name='Fitpeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='适用人数')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./upload_img', verbose_name='产品图片')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='五星脚材料')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='风格')),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='面料材质')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产品名称')),
                ('ename', models.CharField(max_length=50, unique=True, verbose_name='英文名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('con', models.CharField(max_length=100, unique=True, verbose_name='简介')),
                ('desc', models.CharField(max_length=50, unique=True, verbose_name='描述')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('price', models.FloatField(verbose_name='价格')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存')),
                ('content', models.TextField(verbose_name='商品详情')),
                ('c_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='分类')),
                ('color', models.ManyToManyField(to='goods.Color', verbose_name='颜色')),
                ('fitpeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Fitpeople', verbose_name='适用人数')),
                ('img', models.ManyToManyField(to='goods.Image', verbose_name='产品图片')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Materials', verbose_name='五星脚材料')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Style', verbose_name='风格')),
                ('texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Texture', verbose_name='面料材质')),
            ],
        ),
    ]
