# Generated by Django 2.2.1 on 2019-06-25 10:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='商品详情'),
        ),
    ]
